[package]
authors = ["Connor Slade <connor@connorcode.com>"]
name = "journey_to_the_moon"
version = "1.0.1"
edition = "2018"

[dependencies]
afire = { version = "0.1.6", features = ["logging"] }
simple_config_parser = "0.1.6"
serde_json = "1.0.68"
