[package]
authors = ["Connor Slade <connor@connorcode.com>"]
name = "journey_to_the_moon"
version = "1.0.2"
edition = "2018"

[dependencies]
afire = { version = "0.2.0", features = ["logging"] }
simple_config_parser = "1.0.0"
serde_json = "1.0.68"
